title: Peer Mo Mydeen
logo: /assets/img/headshot_circle.png
description: Senior Software Engineer at Microsoft | Data & AI | Software Engineering | Architecture | Data Governance | Azure | Multi-cloud | Cross-cloud | Power Platform
show_downloads: true
theme: jekyll-theme-minimal
